/**
 * @file SelfTests.h
 * @brief Every self test, for the run table in selftest.cpp's main() (the definitions are in selftest_*.cpp).
 */
#pragma once

namespace phostest {

void testParams();   ///< selftest_basics.cpp
void testTempo();   ///< selftest_basics.cpp
void testHalfband();   ///< selftest_basics.cpp
void testLadder();   ///< selftest_basics.cpp
void testMidi();   ///< selftest_basics.cpp
void testWav();   ///< selftest_basics.cpp
void testLoudness();   ///< selftest_basics.cpp
void testOscillator();   ///< selftest_basics.cpp
void testKick();   ///< selftest_basics.cpp
void testBass();   ///< selftest_basics.cpp
void testComposer();   ///< selftest_basics.cpp
void testBassModel();   ///< selftest_basics.cpp
void testVarietyPlans();   ///< selftest_basics.cpp
void testVarietyLevelMatch();   ///< selftest_basics.cpp
void testVarietyRecipes();   ///< selftest_basics.cpp
void testEngine();   ///< selftest_basics.cpp
void testKickReference();   ///< selftest_basics.cpp
void testBassBite();   ///< selftest_basics.cpp
void testKickBody();   ///< selftest_basics.cpp
void testAcidVoicingCorners();   ///< selftest_lowend.cpp
void testAcidVoicingNight();   ///< selftest_lowend.cpp
void testAcidVoicingEngine();   ///< selftest_lowend.cpp
void testRecipeSpread();   ///< selftest_lowend.cpp
void testPercTempo();   ///< selftest_lowend.cpp
void testPhaseLockLock();   ///< selftest_lowend.cpp
void testPhaseLockOnsets();   ///< selftest_lowend.cpp
void testBassRhythm();   ///< selftest_lowend.cpp
void testMidiKeys();   ///< selftest_lowend.cpp
void testPercKit();   ///< selftest_lowend.cpp
void testRhythm();   ///< selftest_lowend.cpp
void testSampler();   ///< selftest_lowend.cpp
void testModelKernel();   ///< selftest_lowend.cpp
void testModelFile();   ///< selftest_lowend.cpp
void testModelDecode();   ///< selftest_lowend.cpp
void testMelodyModelWiring();   ///< selftest_lowend.cpp
void testDiodeLadder();   ///< selftest_synths.cpp
void testAcid();   ///< selftest_synths.cpp
void testPoly();   ///< selftest_synths.cpp
void testAcidColour();   ///< selftest_synths.cpp
void testMelodyScore();   ///< selftest_synths.cpp
void testMelodyVariety();   ///< selftest_synths.cpp
void testMelodyDepthRender();   ///< selftest_synths.cpp
void testMelodyBlockSize();   ///< selftest_synths.cpp
void testMelodyMidi();   ///< selftest_synths.cpp
void testWaveTable();   ///< selftest_synths.cpp
void testProbeAudit();   ///< selftest_synths.cpp
void testMeasure();   ///< selftest_synths.cpp
void testWaveTableLibrary();   ///< selftest_synths.cpp
void testLoaderThreadSafety();   ///< selftest_synths.cpp
void testWaveTableQuality();   ///< selftest_synths.cpp
void testPads();   ///< selftest_synths.cpp
void testGateAndDuck();   ///< selftest_mix.cpp
void testReverb();   ///< selftest_mix.cpp
void testGatedReverb();   ///< selftest_mix.cpp
void testDynamics();   ///< selftest_mix.cpp
void testSfx();   ///< selftest_mix.cpp
void testWanderingFx();   ///< selftest_mix.cpp
void testPsychedelia();   ///< selftest_mix.cpp
void testMaster();   ///< selftest_mix.cpp
void testSfxLevel();   ///< selftest_mix.cpp
void testMixBalance();   ///< selftest_mix.cpp
void testBandLimit();   ///< selftest_mix.cpp
void testStereoWidth();   ///< selftest_mix.cpp
void testModalInterchangeBass();   ///< selftest_mix.cpp
void testModalInterchangeModes();   ///< selftest_mix.cpp
void testModalInterchangePresenceOn1();   ///< selftest_composer.cpp
void testModalInterchangePresenceOn2();   ///< selftest_composer.cpp
void testModalInterchangePresenceOff1();   ///< selftest_composer.cpp
void testModalInterchangePresenceOff2();   ///< selftest_composer.cpp
void testModalInterchangePresenceArcOn1();   ///< selftest_composer.cpp
void testModalInterchangePresenceArcOn2();   ///< selftest_composer.cpp
void testModalInterchangePresenceArcOff1();   ///< selftest_composer.cpp
void testModalInterchangePresenceArcOff2();   ///< selftest_composer.cpp
void testModalInterchangeNewTone();   ///< selftest_composer.cpp
void testModeColour();   ///< selftest_composer.cpp
void testTensionCurve();   ///< selftest_composer.cpp
void testMotifOperators();   ///< selftest_composer.cpp
void testArpPatterns();   ///< selftest_composer.cpp
void testAudibilityMatch();   ///< selftest_composer.cpp
void testAudibility();   ///< selftest_composer.cpp
void testStems();   ///< selftest_composer.cpp
void testDeferredPlan();   ///< selftest_composer.cpp
void testPlanCacheLive();   ///< selftest_composer.cpp
void testSoundPresets();   ///< selftest_composer.cpp
void testKeyboard();   ///< selftest_composer.cpp
void testKnobFuzz();   ///< selftest_composer.cpp
void testPreferences();   ///< selftest_composer.cpp
void testSoloTrack();   ///< selftest_composer.cpp
void testGallery();   ///< selftest_composer.cpp
void testMidiMap();   ///< selftest_composer.cpp
void testRatings();   ///< selftest_composer.cpp
void testSetArc();   ///< selftest_composer.cpp
void testForm();   ///< selftest_composer.cpp
void testArrangeDynamics();   ///< selftest_composer.cpp
void testSectionRules();   ///< selftest_composer.cpp
void testCuration();   ///< selftest_composer.cpp
void testCues();   ///< selftest_composer.cpp
void testTransitions();   ///< selftest_composer.cpp
void testArrangement();   ///< selftest_arrangement.cpp
void testClimax();   ///< selftest_arrangement.cpp
void testPresence();   ///< selftest_arrangement.cpp
void testGenreRulesRules();   ///< selftest_arrangement.cpp
void testGenreRulesPadNoFlat9();   ///< selftest_arrangement.cpp
void testGenreRulesHeldNoFlat9();   ///< selftest_arrangement.cpp
void testGenreRulesBassAndDrone();   ///< selftest_arrangement.cpp
void testGenreRulesCounterAgainstLead();   ///< selftest_arrangement.cpp
void testSfxToneIntervals();   ///< selftest_mix.cpp
void testMixGuideMatrix();   ///< selftest_mixguide.cpp
void testMixGuideLeadDucks();   ///< selftest_mixguide.cpp
void testMixGuidePlanes();   ///< selftest_mixguide.cpp
void testMixGuideDistance();   ///< selftest_mixguide.cpp
void testMixGuidePhase();   ///< selftest_mixguide.cpp
void testFilterModelsLevels();   ///< selftest_modulation.cpp
void testModulationBlockSize();   ///< selftest_modulation.cpp
void testModulationSync();   ///< selftest_modulation.cpp
void testModulationFilterAdsr();   ///< selftest_modulation.cpp
void testPresetBank();   ///< selftest_modulation.cpp
void testGenreRulesListeningSeed();   ///< selftest_arrangement.cpp
void testGenreRulesArpGate();   ///< selftest_arrangement.cpp
void testFoundationScore();   ///< selftest_arrangement.cpp
void testFoundationRender();   ///< selftest_arrangement.cpp
void testVoicesScore();   ///< selftest_arrangement.cpp
void testVoicesDroneRender();   ///< selftest_arrangement.cpp
void testBedAudible();   ///< selftest_arrangement.cpp
void testVoicesSound();   ///< selftest_arrangement.cpp
void testVoicesCounterSoundListening();   ///< selftest_arrangement.cpp
void testVoicesCounterSound77();   ///< selftest_arrangement.cpp
void testVoicesCounterSound2026();   ///< selftest_arrangement.cpp
void testVoicesAcidRide();   ///< selftest_arrangement.cpp
void testDialogueScore();   ///< selftest_arrangement.cpp
void testDialogueGlide();   ///< selftest_arrangement.cpp
void testDialogueSound();   ///< selftest_arrangement.cpp
void testDialogueLevels();   ///< selftest_arrangement.cpp

} // namespace phostest
