/**
 * @file Corpus.h
 * @brief Statistics of the local psytrance MIDI corpus, and the models built on them.
 *
 * Core/src/CorpusTables.cpp is generated by Tools/corpus/build_corpus.py from the MIDI loops on the
 * build machine (acid riffs and sequences, leads and melodies, arps). It holds counts only: pitch
 * successions of order 0 to 2 over the interval to the tonic, onset, accent, slide and length counts
 * per sixteenth step, ambitus, and chord-root successions estimated bar by bar from the arps.
 *
 * **Pitch model.** A variable-order Markov model over the interval to the tonic (-12 .. +24 semitones)
 * with Witten-Bell interpolation: the order-2 estimate is mixed with the order-1 estimate, and that
 * with the order-0 one, each weighted by how much its context has been seen relative to how many
 * different continuations followed it (Witten and Bell, "The zero-frequency problem", IEEE Trans.
 * Inf. Theory 1991; the escape mechanism of PPM-C, compared for music by Begleiter, El-Yaniv and Yona,
 * "On prediction using variable order Markov models", JAIR 2004).
 *
 * **Constrained generation.** Melodies are drawn from this model under unary constraints -- an
 * allowed set of pitches at every position (scale, ambitus, chord tones on strong steps, a start and
 * an end). Rejecting and redrawing would distort the distribution and could loop forever; instead the
 * probability of being able to complete the sequence from every state is computed backwards and the
 * forward draw is weighted by it, which samples exactly from the model conditioned on the
 * constraints (Pachet and Roy, "Markov constraints: steerable generation of Markov sequences",
 * Constraints 16(2), 2011). With an order-2 model the state is the pair of the last two pitches.
 */
#pragma once
#include <cstdint>
#include <vector>

namespace phos {

constexpr int kCorpusRelMin = -12;   ///< lowest interval to the tonic in the alphabet
constexpr int kCorpusRelMax = 24;    ///< highest
constexpr int kCorpusAlphabet = kCorpusRelMax - kCorpusRelMin + 1;   ///< 37 symbols

/** @brief One n-gram count: key = symbols in base kCorpusAlphabet, most significant first. */
struct CorpusGram { uint32_t key; uint32_t count; };

/** @brief The tables of one role. */
struct CorpusRole {
    const char* name;                   ///< "acid", "lead", "arp"
    int files;                          ///< melodic loops that contributed
    const uint32_t* uni;                ///< order-0 counts, kCorpusAlphabet entries
    const CorpusGram* bi;               ///< order-1 counts, sorted by key
    int numBi;
    const CorpusGram* tri;              ///< order-2 counts, sorted by key
    int numTri;
    const uint32_t (*onset)[2][2];      ///< [step][previous step had onset][this step has onset]
    const uint32_t (*accent)[2];        ///< [step][accented]
    const uint32_t (*slide)[2];         ///< [step][slides into the next]
    const uint32_t (*length)[9];        ///< [step][length in steps, 8 = eight or more]
    const uint32_t* ambitus;            ///< [semitones 0..36]
};

/** @brief Roles in the tables. */
enum class CorpusRoleId : int { Acid = 0, Lead, Arp, Count };
constexpr int kNumCorpusRoles = static_cast<int>(CorpusRoleId::Count);
extern const CorpusRole kCorpusRoles[kNumCorpusRoles];

extern const uint32_t kCorpusChordTransitions[12][12];   ///< bar-to-bar chord roots, interval to the tonic
extern const uint32_t kCorpusChordFirst[12];             ///< first chord root of a loop
extern const int kCorpusChordFiles;                      ///< arp loops that contributed

/** @brief Witten-Bell interpolated variable-order pitch model of one role. */
class PitchModel {
public:
    /** @brief Builds the dense probability tables of @p role (once, at start-up). */
    explicit PitchModel(CorpusRoleId role);
    /** @brief P(next | prev2, prev1), symbols 0..kCorpusAlphabet-1. */
    double prob(int prev2, int prev1, int next) const
    {
        return p_[static_cast<size_t>((prev2 * kCorpusAlphabet + prev1) * kCorpusAlphabet + next)];
    }
    /** @brief Symbol of an interval to the tonic. */
    static int symbol(int rel) { return rel - kCorpusRelMin; }
    /** @brief Interval to the tonic of a symbol. */
    static int rel(int symbol) { return symbol + kCorpusRelMin; }
    /** @brief Number of symbols. */
    int alphabet() const { return kCorpusAlphabet; }

private:
    std::vector<double> p_;
};

/**
 * @brief Draws a sequence from an order-2 model under per-position allowed sets (Pachet and Roy).
 * @tparam Model  anything with int alphabet() and double prob(a, b, c) (PitchModel, or a toy model in the tests)
 * @param model   the model
 * @param allowed allowed[i][s] != 0 when symbol s may stand at position i; the value is a relative
 *                weight, so that one symbol may be preferred over another at the same position (all
 *                entries equal = the plain constraint, which is what a set of ones gives)
 * @param start2,start1 context before the first position (symbols)
 * @param temperature exponent 1/T applied to the model's probabilities (1 = the model as it is)
 * @param uniform source of uniform numbers in [0, 1)
 * @param out     receives the symbols
 * @return false if no sequence satisfies the constraints
 */
template <class Model, class Uniform>
bool sampleConstrained(const Model& model, const std::vector<std::vector<uint8_t>>& allowed, int start2, int start1,
                       double temperature, Uniform&& uniform, std::vector<int>& out);

/** @brief Chord-root succession probabilities (with add-one smoothing over the roots seen at all). */
double chordTransition(int fromRel, int toRel);

} // namespace phos

#include "phos/CorpusSample.inl"
