/**
 * @file WaveTableList.inl
 * @brief The library tables this build ships -- generated by `Tools/wt_pack.py`, do not edit.
 *
 * Included twice: bare, for `PHOS_WT_LIBRARY_COUNT`, and with `PHOS_WT(index, name, id,
 * lane, fallback)` defined, to build a list. The order is the order the `table` parameter's
 * indices follow after the six built-in tables, and it must not be reshuffled: a `.phosset`
 * stores the index.
 */
#ifndef PHOS_WT_LIBRARY_COUNT
#define PHOS_WT_LIBRARY_COUNT 12
#endif

#ifdef PHOS_WT
PHOS_WT(0, "WaveEdit Hyperbol", "Classic/wavedit_hyperbol", WaveTableLane::Pad, 1)
PHOS_WT(1, "Sampled 210", "Ambient/ambient_sampled_210", WaveTableLane::Pad, 2)
PHOS_WT(2, "WaveEdit Sohler52", "Classic/wavedit_sohler52", WaveTableLane::Pad, 5)
PHOS_WT(3, "Organ 034", "Harmonic/harmonic_organ_034", WaveTableLane::Pad, 1)
PHOS_WT(4, "Otmorph 069", "Ambient/ambient_otmorph_069", WaveTableLane::Pad, 2)
PHOS_WT(5, "WaveEdit Hienharm", "Classic/wavedit_hienharm", WaveTableLane::Lead, 4)
PHOS_WT(6, "WaveEdit Junox_ho", "Classic/wavedit_junox_ho", WaveTableLane::Lead, 3)
PHOS_WT(7, "WaveEdit Euclidea", "Classic/wavedit_euclidea", WaveTableLane::Lead, 4)
PHOS_WT(8, "WaveEdit Sohler49", "Classic/wavedit_sohler49", WaveTableLane::Lead, 3)
PHOS_WT(9, "Consonant 129", "Ambient/ambient_consonant_129", WaveTableLane::Arp, 3)
PHOS_WT(10, "AKWF 0004-hollow-01", "Classic/akwf_0004_hollow_01", WaveTableLane::Arp, 4)
PHOS_WT(11, "WaveEdit Pd104", "Classic/wavedit_pd104", WaveTableLane::Arp, 3)
#endif
