// Generated by Tools/field_archives.py -- do not edit.
#define FieldSet "1"
#define FieldBaseUrl "https://github.com/reneweller-coding/Phosphene/releases/download/field-data-1"
#define FieldZipA "Phosphene-field-1a.zip"
#define FieldZipASha256 "af069ed3591e4e8834aed173c60432840a81ef69bd2055fe0777c8645479698c"
#define FieldZipB "Phosphene-field-1b.zip"
#define FieldZipBSha256 "18750f75ad79f3b3fc2525a6252c7255d84c09311bfbe4f0d2f5735c02cb64e4"
#define FieldMarkerSha256 "7ee097c3508a3764fd35ae7a2efecaecb2e2e1dcb783ee93b07e38f3f9e71cce"
#define FieldSizeMB "1975"
