# The core's build id (round "speed", 20.09.2026): one hash over everything that decides what the core
# computes -- every file under Core/src and Core/include, and the compiler with its flags -- written as
# phos_build_id.h for Core/src/Probe.cpp. It is one part of every probe-cache key (Probe.h): an entry stored
# by another core must never be served, because a probe's numbers are that core's numbers.
#
# Run as a script at *build* time (Core/CMakeLists.txt, target phos_build_id), not at configure time: the
# sources change between two builds of one configured tree, and that is exactly the case the id exists for.
# 0.1 s for about 80 files. The header is rewritten only when the id changed, so an unchanged core does not
# recompile Probe.cpp, and a changed one recompiles nothing but Probe.cpp on top of what changed anyway.
#
#   PHOS_CORE_DIR    Core/
#   PHOS_FLAGS_FILE  a file holding compiler id, version and flags of this configuration
#   PHOS_OUT         the header to write
file(GLOB_RECURSE _files LIST_DIRECTORIES false "${PHOS_CORE_DIR}/src/*" "${PHOS_CORE_DIR}/include/*")
list(SORT _files)
set(_all "")
foreach(_f IN LISTS _files)
    file(SHA256 "${_f}" _h)
    file(RELATIVE_PATH _rel "${PHOS_CORE_DIR}" "${_f}")
    string(APPEND _all "${_rel}=${_h}\n")
endforeach()
if(EXISTS "${PHOS_FLAGS_FILE}")
    file(READ "${PHOS_FLAGS_FILE}" _flags)
    string(APPEND _all "flags=${_flags}\n")
endif()
string(SHA256 _id "${_all}")
string(SUBSTRING "${_id}" 0 32 _id)
set(_text "// Generated by Core/cmake/build_id.cmake at build time; do not edit.\n#define PHOS_BUILD_ID \"${_id}\"\n")
set(_old "")
if(EXISTS "${PHOS_OUT}")
    file(READ "${PHOS_OUT}" _old)
endif()
if(NOT _old STREQUAL _text)
    file(WRITE "${PHOS_OUT}" "${_text}")
endif()
