"""Writes Core/src/PresetBankData.inl from Tools/presets/bank_spec.py (26.09.2026).

    python Tools/presets/gen_bank.py

Checks what the C++ side cannot see at a glance: eight adjectives and eight nouns everywhere, sixteen groups per synth,
every preset name unique within its synth, every archetype a group names defined.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import bank_spec as S  # noqa: E402

OUT = os.path.join(HERE, "..", "..", "Core", "src", "PresetBankData.inl")


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def knob(k):
    key, lo, hi, axis = k
    ax = "'" + axis + "'"
    if key == "table":
        return f"{{ {cstr(key)}, 0.0f, 0.0f, {ax}, {cstr(lo)} }}"
    return f"{{ {cstr(key)}, {float(lo)!r}f, {float(hi)!r}f, {ax}, nullptr }}"


def group_code(name, nouns, arch, aname):
    knobs = ", ".join(knob(k) for k in arch.get("knobs", []))
    filters = ", ".join(f"{{ {m}, {float(a)!r}f, {float(b)!r}f }}" for m, a, b in arch.get("filters", []))
    mods = ", ".join(f"{{ {float(ch)!r}f, {{ {', '.join(knob(k) for k in ks)} }} }}" for ch, ks in arch.get("mods", []))
    w = S.GROUP_STYLE.get(name, S.ARCH_STYLE.get(aname, (1, 1, 1, 1, 1)))
    styles = ", ".join(f"{float(x)!r}f" for x in w)
    return (f"        {{ {cstr(name)}, {{ {', '.join(cstr(n) for n in nouns)} }}, {{ {styles} }},\n"
            f"          {{ {knobs} }},\n          {{ {filters} }},\n          {{ {mods} }} }}")


def synth_code(label, module, instance, adj, groups, arch):
    assert len(adj) == 8, label
    assert len(groups) == 16, (label, len(groups))
    names = set()
    parts = []
    for gname, aname, nouns in groups:
        assert len(nouns) == 8, (label, gname)
        a = arch[aname]
        if isinstance(a, list):
            a = dict(knobs=a)
        for r in adj:
            for n in nouns:
                nm = r + " " + n
                assert nm not in names, (label, nm)
                names.add(nm)
        assert aname in S.ARCH_STYLE, (label, aname)
        parts.append(group_code(gname, nouns, a, aname))
    return (f"    {{ {cstr(label)}, Module::{module}, {instance}, {{ {', '.join(cstr(a) for a in adj)} }}, {{\n"
            + ",\n".join(parts) + "\n    } }")


def main():
    synths = []
    for label, v in S.VOICE_SYNTHS.items():
        synths.append(synth_code(label, "Poly", v["instance"], v["adj"], v["groups"], S.ARCH))
    synths.append(synth_code("bass", "Bass", 0, S.BASS_SYNTH["adj"], S.BASS_SYNTH["groups"], S.BASS_ARCH))
    synths.append(synth_code("acid", "Acid", 0, S.ACID_SYNTH["adj"], S.ACID_SYNTH["groups"], S.ACID_ARCH))
    synths.append(synth_code("kick", "Kick", 0, S.KICK_SYNTH["adj"], S.KICK_SYNTH["groups"], S.KICK_ARCH))
    text = ("// Generated by Tools/presets/gen_bank.py from Tools/presets/bank_spec.py -- do not edit; edit the spec.\n"
            "// Included by PresetBank.cpp inside namespace phos::bank.\n"
            "/** @brief Every synth's bank of presets (Tools/presets/bank_spec.py), built on first use. */\n"
            "const std::vector<Synth>& synths()\n{\n    static const std::vector<Synth> k = {\n"
            + ",\n".join(synths) + "\n    };\n    return k;\n}\n")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {OUT}: {len(synths)} synths x 16 groups x 64 presets")


if __name__ == "__main__":
    main()
