"""Packs the Field track's recordings for the setup's download (27.09.2026).

    python Tools/field_archives.py [--out Deploy/out] [--set 1]

`Core/data/field` (Tools/field_select.py: 157 original FLAC files, 1.97 GB) goes into two archives,
`Phosphene-field-<set>a.zip` and `-<set>b.zip`, each about half: GitHub takes no release file over 2 GB, and a
download of one gigabyte that breaks costs less than one of two. The FLAC files are stored, not deflated (they are
already compressed; deflating them only costs time). Inside, the paths start with `field/`, so both archives unpack
into the same folder beside each other.

The archives belong to a release of their own, `field-data-<set>`, and not to each version's: the recordings change
far less often than the program, and a setup of a later version downloads the same set without anybody uploading two
gigabytes again. A new selection is a new set number.

Writes `Deploy/field-files.iss` (the names, the archives' SHA-256, the release's address and the hash of
`field/CREDITS-field.md`, by which the setup recognises an installed set and downloads nothing). Upload once:

    gh release create field-data-1 Deploy/out/Phosphene-field-1a.zip Deploy/out/Phosphene-field-1b.zip \\
        --repo reneweller-coding/Phosphene --title "Field recordings, set 1" --notes "..."
"""
import argparse
import hashlib
import os
import shutil
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIELD = os.path.join(ROOT, "Core", "data", "field")
CREDITS = os.path.join(ROOT, "Core", "data", "CREDITS-field.md")
ISS = os.path.join(ROOT, "Deploy", "field-files.iss")
REPO = "https://github.com/reneweller-coding/Phosphene/releases/download"


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "Deploy", "out"))
    ap.add_argument("--set", default="1")
    a = ap.parse_args()
    if not os.path.isdir(FIELD):
        raise SystemExit("no Core/data/field -- run Tools/field_select.py first")
    # The credits travel with the recordings: the setup's marker, and what a user of the folder reads.
    shutil.copy2(CREDITS, os.path.join(FIELD, "CREDITS-field.md"))
    files = []
    for dp, _, fs in os.walk(FIELD):
        for f in sorted(fs):
            p = os.path.join(dp, f)
            files.append((os.path.relpath(p, os.path.dirname(FIELD)).replace("\\", "/"), p, os.path.getsize(p)))
    files.sort()
    total = sum(s for _, _, s in files)
    # Two halves by size, in name order (a category stays together as far as the halves allow).
    half, acc, parts = total / 2, 0, ([], [])
    for f in files:
        parts[0 if acc < half else 1].append(f)
        acc += f[2]
    os.makedirs(a.out, exist_ok=True)
    names = []
    for tag, part in zip("ab", parts):
        name = "Phosphene-field-%s%s.zip" % (a.set, tag)
        path = os.path.join(a.out, name)
        with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_STORED, allowZip64=True) as z:
            for arc, p, _ in part:
                z.write(p, arc)
        names.append((name, sha256(path), os.path.getsize(path)))
        print("%s: %d files, %.2f GB" % (name, len(part), os.path.getsize(path) / 1e9))
    lines = ["// Generated by Tools/field_archives.py -- do not edit.",
             '#define FieldSet "%s"' % a.set,
             '#define FieldBaseUrl "%s/field-data-%s"' % (REPO, a.set),
             '#define FieldZipA "%s"' % names[0][0], '#define FieldZipASha256 "%s"' % names[0][1],
             '#define FieldZipB "%s"' % names[1][0], '#define FieldZipBSha256 "%s"' % names[1][1],
             '#define FieldMarkerSha256 "%s"' % sha256(os.path.join(FIELD, "CREDITS-field.md")),
             '#define FieldSizeMB "%d"' % round(total / 1e6)]
    open(ISS, "w", encoding="utf-8", newline="\r\n").write("\n".join(lines) + "\n")
    print("-> %s" % ISS)


if __name__ == "__main__":
    main()
